name: Pull Request
"on":
  - pull_request
jobs:
  install:
    name: Installing Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies for cliente
        run: cd ./cliente && yarn install
      - name: Install dependencies for pedidos
        run: cd ./pedidos && yarn install
      - name: Install dependencies for produto
        run: cd ./produto && yarn install
  test-setup:
    name: Setup Jest
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Check Jest installation for cliente
        run: |
          echo "Current directory: $(pwd)"
          cd ../cliente && yarn list jest || exit 1

      - name: Check Jest installation for pedidos
        run: |
          echo "Current directory: $(pwd)"
          cd ../pedidos && yarn list jest || exit 1

      - name: Check Jest installation for produto
        run: |
          echo "Current directory: $(pwd)"
          cd ../produto && yarn list jest || exit 1
  # unusedexports:
  #   name: Find unused exports (dead code)
  #   runs-on: ubuntu-latest
  #   needs: install
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Prune for API Cliente
  #       run: cd cliente/ && yarn ts-prune --error
  #     - name: Prune for API Pedidos
  #       run: cd pedidos/ && yarn ts-prune --error
  #     - name: Prune for API Produto
  #       run: cd produto/ && yarn ts-prune --error
  testing:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs:
      - install
      - test-setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run unit tests for API Cliente
        run: |
          echo "Current directory: $(pwd)"
          cd cliente/
          echo "Current directory (after cd cliente/): $(pwd)"
          yarn test
      - name: Run unit tests for API Pedidos
        run: |
          echo "Current directory: $(pwd)"
          cd pedidos/
          echo "Current directory (after cd pedidos/): $(pwd)"
          yarn test
      - name: Run unit tests for API Produto
        run: |
          echo "Current directory: $(pwd)"
          cd produto/
          echo "Current directory (after cd produto/): $(pwd)"
          yarn test
