name: Pull Request

on: [pull_request]

jobs:
  install:
    name: Installing Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install

  unusedexports:
    name: Find unused exports (dead code)
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        api:
          - cliente
          - pedidos
          - produto
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Navigate to API directory
        run: cd ${{ matrix.api }}
      - name: Run ts-prune for API ${{ matrix.api }}
        run: yarn ts-prune --error

  testing:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: install
    strategy:
      matrix:
        api:
          - cliente
          - pedidos
          - produto
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Navigate to API directory
        run: cd ${{ matrix.api }}
      - name: Run unit tests for API ${{ matrix.api }}
        run: yarn test