name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  install:
    name: Installing Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies for cliente
        run: |
          cd ./cliente 
          yarn install
      - name: Install dependencies for pedidos
        run: |
          cd ./pedidos
          yarn install
          yarn add @types/jest
      - name: Install dependencies for produto
        run: |
          cd ./produto
          yarn install
          yarn add @types/jest

  testing:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs:
      - install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run unit tests for API Cliente
        run: |
          ls
          echo "Current directory: $(pwd)" 
          cd cliente/
          ls
          echo "Current directory: $(pwd)" 
          yarn jest
          cat package.json
      - name: Run unit tests for API Pedidos
        run: |
          cd pedidos/
          yarn jest
      - name: Run unit tests for API Produto
        run: |
          cd produto/
          yarn jest
